# Generated by Django 5.0.7 on 2024-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('paymentDateTime', models.DateTimeField(auto_now_add=True)),
                ('paymentMethod', models.CharField(choices=[('Tarjeta de Credito', 'Tarjeta de Credito'), ('Tarjeta de Debito', 'Tarjeta de Debito'), ('Transferencia Bancaria ', 'Transferencia Bancaria '), ('MercadoPago', 'MercadoPago')], max_length=30)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Fallido', 'Fallido')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorksPaid',
            fields=[
                ('worksPaidID', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodPaidFrom', models.DateField()),
                ('periodPaidTo', models.DateField()),
                ('hoursPaid', models.FloatField()),
            ],
        ),
    ]
