# Generated by Django 5.0.7 on 2024-09-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contracts', '0002_initial'),
        ('Payments', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='Users.userprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='workerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Users.userworkdata'),
        ),
        migrations.AddField(
            model_name='workspaid',
            name='contractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts.contract'),
        ),
        migrations.AddField(
            model_name='workspaid',
            name='paymentID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Payments.payment'),
        ),
    ]
