# Generated by Django 5.0.7 on 2024-09-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('healthInsuranceID', models.BigAutoField(primary_key=True, serialize=False)),
                ('healthInsuranceName', models.CharField(max_length=255)),
                ('inscriptionNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsuranceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthInsuranceProvinces', models.CharField(max_length=255)),
                ('healthInsuranceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='HealthInsurance.healthinsurance')),
            ],
        ),
    ]
