# Generated by Django 5.0.7 on 2024-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checklistID', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('taskDescription', models.TextField()),
                ('taskDateTime', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('doneDateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComfortOffered',
            fields=[
                ('comfortID', models.BigAutoField(primary_key=True, serialize=False)),
                ('comfortName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractID', models.BigAutoField(primary_key=True, serialize=False)),
                ('contractStartTime', models.DateTimeField()),
                ('contractEndTime', models.DateTimeField()),
                ('contractStatus', models.CharField(max_length=50)),
                ('contractDescription', models.TextField()),
                ('maxPaymentProposed', models.FloatField()),
                ('taskList', models.BooleanField(default=False)),
                ('profesionalRequired', models.CharField(max_length=50)),
                ('specialRequirement', models.TextField()),
                ('contractLocation', models.CharField(max_length=255)),
                ('paymentAgreed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillRequired',
            fields=[
                ('skillRequiredID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
