# Generated by Django 5.0.7 on 2024-09-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contracts', '0001_initial'),
        ('Patients', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='workerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='Users.userworkdata'),
        ),
        migrations.AddField(
            model_name='contract',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient'),
        ),
        migrations.AddField(
            model_name='contract',
            name='skillRequired',
            field=models.ManyToManyField(to='Users.skilllist'),
        ),
        migrations.AddField(
            model_name='contract',
            name='userMakerID',
            field=models.ManyToManyField(related_name='made_contracts', to='Users.userprofile'),
        ),
        migrations.AddField(
            model_name='contract',
            name='userReceiverID',
            field=models.ManyToManyField(related_name='received_contracts', to='Users.userworkdata'),
        ),
        migrations.AddField(
            model_name='comfortoffered',
            name='contractID',
            field=models.ManyToManyField(related_name='comforts_offered', to='Contracts.contract'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='contractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='Contracts.contract'),
        ),
        migrations.AddField(
            model_name='skillrequired',
            name='contractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contracts.contract'),
        ),
        migrations.AddField(
            model_name='skillrequired',
            name='skillID',
            field=models.ManyToManyField(to='Users.skilllist'),
        ),
    ]
