# Generated by Django 5.0.7 on 2024-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.BigAutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=255)),
                ('courseSkill', models.CharField(max_length=255)),
                ('courseDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('courseID', models.ManyToManyField(related_name='students', to='Courses.course')),
            ],
        ),
    ]
