# Generated by Django 5.0.7 on 2024-09-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HealthInsurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.BigAutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=50)),
                ('patientSurname', models.CharField(max_length=50)),
                ('patientGender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=10)),
                ('patientBirthDate', models.DateField()),
                ('patientDescription', models.TextField(blank=True, null=True)),
                ('patientFIMScale', models.PositiveSmallIntegerField()),
                ('healthInsuranceMemberID', models.PositiveIntegerField()),
                ('healthInsuranceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthInsurance.healthinsurance')),
            ],
        ),
        migrations.CreateModel(
            name='BarthelScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientBarthelActivity', models.CharField(max_length=100)),
                ('patientBarthelPoint', models.PositiveSmallIntegerField()),
                ('patientID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCurrentDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseName', models.CharField(max_length=100)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCurrentTreatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentsName', models.CharField(max_length=100)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
    ]
